services:
  infra:
    user: "root"
    container_name: novnc-testing
    volumes:
      - ./:/opt/novnc:rw
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    tty: true
    stdin_open: true

# UNCOMMENT IF WORKING ON SERVER
#     networks:
#       - swarm_net

# networks:
#   swarm_net:
#     external: true
#     name: swarm-stack_vnc_net
    